name: Run arXiv Periodically

on:
  schedule:
    # * is a special character in YAML; it has to be quoted
    - cron:  '0 13 * * *'
    # run every 30 minutes
    # - cron: '30 * * * *'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run main
      env:
        SLACK_KEY: ${{ secrets.SLACK_KEY }}
        SLACK_CHANNEL_ID: ${{ secrets.SLACK_CHANNEL_ID }}
      run: |
        python main.py
    - name: Upload results
      uses: actions/upload-artifact@v3
      with:
        name: arxiv-scanner-outputs
        path: data/
        retention-days: 5